config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'signup' => 'users#new'
  get 'users/:id/likes' => 'users#likes'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :posts do
    resources :likes, :only => [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :name, presence: true, length: { maximum: 50 }
  validates :image, presence: true
  validates :comment, length: { maximum: 300 }
  validates :user_id, presence: true

  def user
    User.find(self.user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 9)
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "投稿しました！"
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:seccess] = "投稿内容を変更しました！"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:seccess] = "投稿内容を削除しました"
    redirect_to posts_url
  end

  private

    def post_params
      params.require(:post).permit(:name, :price,
                    :store, :address, :image, :comment)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/post/error_messages', object: @post %>

  <%= f.label :image, "アップロード画像" %>
  <%= f.file_field :image, accept: 'image/jpg image/jpeg image/gif image/png' %>

  <%= f.label :name, "商品名" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :price, "値段（任意）" %>
  <%= f.number_field :price, class: 'form-control' %>

  <%= f.label :store, "お店の名前（任意）" %>
  <%= f.text_field :store, class: 'form-control' %>

  <%= f.label :address, "お店の住所（任意）" %>
  <%= f.text_field :address, class: 'form-control' %>

  <%= f.label :comment, "コメント（任意）" %>
  <%= f.text_area :comment, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<aside class="col-md-4">
  <section class="post_part">
  <%= link_to image_tag(post.image.url, size: '300x300', alt: "Sweet Image"), post %><br>
  <%= link_to post.name, post %><br>
  (<%= post.liked_users.count %>) <%# 投稿へのいいね数を表示 %>
  <%= link_to "投稿者：#{post.user.name}", user_path(post.user) %>
  </section>
</aside>

app/views/posts/edit.html.erb
<% provide(:button_text, "変更する") %>
<div class="jumbotron jumbotron_width">
  <div class="form_container">
    <h1>変更用フォーム</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<%= will_paginate @posts  %>

<div class="row">
  <%= render @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

<%= will_paginate %>

app/views/posts/new.html.erb
<% provide(:button_text, '投稿する') %>
<div class="jumbotron jumbotron_width">
  <div class="form_container">
    <h1>投稿フォーム</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<section class="post_info">
  <%= image_tag @post.image.url, size: '300x300', class: 'post_image', alt: "Sweet Image" %>
  <p><%= "商品名：#{@post.name}" %></p>
  <p><%= "値段：#{@post.price}円" %></p>
  <p><%= "店名：#{@post.store}" %></p>
  <p><%= "住所：#{@post.address}" %></p>
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.393549832709!2d139.7042476152524!3d35.6673104801975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188d2521e2da3b%3A0xe36e1925efe23b9c!2zRkxJUFBFUidTIOihqOWPgumBk-W6lw!5e0!3m2!1sja!2sjp!4v1601109853876!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  <div class="post_user">
    <%= link_to image_tag(@post.user.avatar.url, size: '80x80', alt: "User Image"), @post.user %>
    <%= link_to "投稿者：#{@post.user.name}", @post.user %>
  </div>
  <p><%= "コメント：#{@post.comment}" %></p>
  <%# <>いいね件数： <%= @post.likes.count %>
  <% if current_user && current_user.already_liked?(@post) %>
    <%# <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
    <%= link_to post_like_path(@post), method: :delete do %>
      <i class="fas fa-thumbs-up"><%= @post.likes.count %></i>
    <% end %>
  <% else %>
    <%# <%= button_to 'いいね', post_likes_path(@post) %>
    <%= link_to post_likes_path(@post), method: :post do %>
      <i class="far fa-thumbs-up"><%= @post.likes.count %></i>
    <% end %>
  <% end %>
  <p>いいねしたユーザー</p>
  <% @post.liked_users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
  <% if current_user && @post.user.id == current_user.id %>
    <%= link_to "変更", edit_post_path, class: "btn btn-primary", role: "button" %>
    <%= link_to "削除", post_path, method: :delete, class: "btn btn-primary", role: "button" %>
  <% end %>
</section>