config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'signup' => 'users#new'
  get 'users/:id/likes' => 'users#likes'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :posts do
    resources :likes, :only => [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= link_to "SweetsBlog", root_path, id: "footer-logo" %>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"> <%# ここから先はみんなbootstrap4を適応 %>
  <div class="container">
    <%= link_to "SweetsBlog", root_path, id: "header-logo" %>
    <nav>
      <ul class="nav navbar-expand-md navbar-nav .justify-content-end">
        <li class="nav-item active"><%= link_to "ホーム", root_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "ヘルプ", help_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: 'nav-link' %></li>
        <% if logged_in? %> <%# ログインしてる人には見える %>
          <li class="nav-item"><%= link_to "投稿する", new_post_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "ユーザー", users_path, class: 'nav-link' %></li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" id="dropdownMenuLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              アカウント<b class="caret"></b>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to current_user.name, current_user, class: 'dropdown-item' %>
              <%= link_to "設定", edit_user_path(current_user), class: 'dropdown-item' %>
              <div class="divider">
              <%= link_to "ログアウト", logout_path, class: 'dropdown-item', method: :delete %>
              <%# <%= link_to "退会", current_user, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
        <% else %>
          <%= link_to "ログイン", login_path, class: 'nav-link' %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all',
                              'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application',
                              'data-turbolinks-track': 'reload' %>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetsApp</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %> <%# ページ上部のメッセージを表示 %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <div class="min-height"> <%# ページ縦幅の最小値を指定 %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %> <%# 開発デバッグようなので変更しないでいい %>
    </div>
  </body>
</html>